"""initial

Revision ID: 1dd63ac08c74
Revises: 4b5cb1e71d42
Create Date: 2026-01-29 10:02:49.070103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd63ac08c74'
down_revision: Union[str, Sequence[str], None] = '4b5cb1e71d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('can_access_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_access_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_access_property', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_add_property', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_edit_property', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_delete_property', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_unlist_property', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('staff_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_pkey')),
    sa.UniqueConstraint('email', name=op.f('staff_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
