"""updated usr table

Revision ID: 5740c57c1025
Revises: 1dd63ac08c74
Create Date: 2026-02-03 17:34:42.759074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5740c57c1025'
down_revision: Union[str, Sequence[str], None] = '1dd63ac08c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
