"""updated usr table

Revision ID: b23ecf8035b0
Revises: 5740c57c1025
Create Date: 2026-02-04 15:08:06.628644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23ecf8035b0'
down_revision: Union[str, Sequence[str], None] = '5740c57c1025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('can_access_dashboard', sa.Boolean(), nullable=True))
    op.add_column('staff', sa.Column('can_access_reports', sa.Boolean(), nullable=True))
    op.add_column('staff', sa.Column('can_access_subscriptions_plans', sa.Boolean(), nullable=True))
    op.drop_column('staff', 'can_access_property')
    op.drop_column('staff', 'can_add_property')
    op.drop_column('staff', 'can_delete_property')
    op.drop_column('staff', 'can_edit_property')
    op.drop_column('staff', 'can_unlist_property')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('can_unlist_property', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('can_edit_property', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('can_delete_property', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('can_add_property', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('can_access_property', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('staff', 'can_access_subscriptions_plans')
    op.drop_column('staff', 'can_access_reports')
    op.drop_column('staff', 'can_access_dashboard')
    # ### end Alembic commands ###
